@HostAddress = http://localhost:5094
###
POST {{HostAddress}}/api/v1/schedules/halls/019d022f-0608-7430-b9fc-172e8a382f40/movies
Accept: application/json
Content-Type: application/json
{
  "movieId": "019d022f-7312-7e79-a653-58b5490d5eb7",
  "startTime": "19:00:00",
  "Price": {
    "Amount": 100,
    "Currency": "TRY"
  }
}
###
GET {{HostAddress}}/api/v1/schedules/halls/019d022f-0608-7430-b9fc-172e8a382f40/movies
Accept: application/json
