@HostAddress = http://localhost:5094
@accessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOWQwMjNmLTQ5MTctN2MwMi05ZTc5LTQ0M2U0MDQyYmExNCIsImVtYWlsIjoiZi1jYWtpcm9nbHVAb3V0bG9vay5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZmNha2lyb2dsdTYxNTciLCJqdGkiOiJmZDYzMjllOC00MGU1LTRiYzMtYmU1MS01OGYyNWZiNmIyZTYiLCJuYmYiOjE3NzM4NTkyMjUsImV4cCI6MTc3Mzg3MzYyNSwiaXNzIjoiYXBpLmNpbmVtYS10aWNrZXRpbmctc3l0ZW0uY29tIn0.NKz9O04gRd4JzerCdWI33ih4bLS_--VtyzLbKIEoEL8

###
POST {{HostAddress}}/api/v1/ticketing/seatholds
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "seatPositions": [
    {
      "row": "A",
      "number": 1
    },
    {
      "row": "B",
      "number": 1
    }
  ],
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "019d0232-d968-7f66-8535-6db57bdf8176"
}

###
POST {{HostAddress}}/api/v1/ticketing/seatholds/confirm
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "019d0232-d968-7f66-8535-6db57bdf8176"
}

###
POST {{HostAddress}}/api/v1/ticketing/issuance
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "019d0232-d968-7f66-8535-6db57bdf8176"
}
###
POST {{HostAddress}}/api/v1/ticketing/reservation
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "0198d099-23eb-7568-9b05-19353f6a54e5"
}
###
POST {{HostAddress}}/api/v1/ticketing/reservation/confirm/0199b0f1-6372-7a3e-9b8a-f1949330fe50
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}
